In [42]:
class MeraLR:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,X_train,y_train):

        num = 0
        den = 0

        for i in range(X_train.shape[0]):
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))

        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,X_test):
        print(X_test)
        return (self.m * X_test) + self.b

In [2]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('sample_placement.csv')

In [6]:
X = df.iloc[:,0].values
y = df.iloc[:,-1].values

In [7]:
X

array([4.2, 4.4, 4.6, 4.7, 4.8, 4.9, 5. , 5. , 5.1, 5.1, 5.2, 5.2, 5.3,
       5.3, 5.4, 5.4, 5.5, 5.5, 5.6, 5.6, 5.7, 5.7, 5.8, 5.8, 5.9, 5.9,
       6. , 6. , 6. , 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.4,
       6.4, 6.4, 6.5, 6.5, 6.5, 6.6, 6.6, 6.6, 6.7, 6.7, 6.7, 6.8, 6.8,
       6.8, 6.9, 6.9, 6.9, 7. , 7. , 7. , 7. , 7.1, 7.1, 7.1, 7.1, 7.2,
       7.2, 7.2, 7.2, 7.3, 7.3, 7.3, 7.3, 7.4, 7.4, 7.4, 7.4, 7.5, 7.5,
       7.5, 7.5, 7.6, 7.6, 7.6, 7.6, 7.7, 7.7, 7.7, 7.7, 7.8, 7.8, 7.8,
       7.8, 7.9, 7.9, 7.9, 7.9, 8. , 8. , 8. , 8. , 8.1, 8.1, 8.1, 8.1,
       8.2, 8.2, 8.2, 8.2, 8.3, 8.3, 8.3, 8.3, 8.4, 8.4, 8.4, 8.4, 8.5,
       8.5, 8.5, 8.5, 8.6, 8.6, 8.6, 8.6, 8.7, 8.7, 8.7, 8.7, 8.8, 8.8,
       8.8, 8.8, 8.9, 8.9, 8.9, 8.9, 9. , 9. , 9. , 9. , 9.1, 9.1, 9.1,
       9.1, 9.2, 9.2, 9.2, 9.2, 9.3, 9.3, 9.3, 9.3, 9.4, 9.4, 9.4, 9.4,
       9.5, 9.5, 9.5, 9.5, 9.6, 9.6, 9.6, 9.6, 6. , 5.5, 7.2, 8.1, 8.8,
       7.5, 6.8, 5.8, 7.9, 8.5, 6.4, 7. , 8.2, 9. , 5.3, 6.7, 7.

In [8]:
y

array([1.55, 1.95, 1.5 , 1.52, 1.53, 1.38, 1.65, 1.82, 1.73, 2.32, 1.88,
       1.67, 2.1 , 1.98, 1.6 , 2.18, 2.23, 1.95, 2.2 , 2.15, 2.32, 2.18,
       2.12, 2.52, 2.28, 2.75, 2.4 , 2.25, 2.65, 2.35, 2.72, 2.48, 2.15,
       2.75, 2.58, 2.82, 2.32, 2.65, 2.55, 2.72, 2.98, 2.45, 2.85, 2.65,
       2.92, 2.35, 2.75, 2.55, 3.05, 2.78, 2.4 , 3.15, 2.92, 2.58, 3.22,
       2.98, 2.72, 3.05, 3.18, 3.52, 2.82, 3.32, 3.1 , 2.95, 3.15, 3.45,
       3.28, 2.92, 3.05, 3.52, 3.15, 2.82, 3.25, 3.48, 3.62, 2.95, 3.02,
       3.72, 3.28, 2.82, 3.12, 3.55, 3.85, 3.22, 3.18, 3.95, 3.62, 2.95,
       3.35, 3.82, 4.05, 3.48, 3.22, 3.95, 3.62, 3.15, 3.45, 4.02, 3.85,
       3.25, 3.52, 4.12, 3.72, 3.35, 3.68, 4.18, 3.82, 3.42, 3.45, 4.22,
       3.92, 3.62, 3.72, 4.28, 3.95, 3.55, 3.85, 4.32, 4.05, 3.62, 3.95,
       4.18, 4.02, 3.48, 4.02, 4.38, 4.12, 3.72, 3.82, 4.62, 4.08, 3.55,
       3.75, 4.58, 4.18, 3.68, 3.85, 4.65, 4.28, 3.82, 4.12, 4.38, 3.72,
       4.02, 3.85, 4.25, 4.12, 3.62, 4.28, 4.42, 4.

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [12]:
X_train.shape

(160,)

In [13]:
lr = MeraLR()

In [16]:
lr.fit(X_train,y_train)

(160,)


In [17]:
lr = MeraLR()

In [22]:
lr.fit(X_train,y_train)

TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'float'

In [23]:
lr.fit(X_train,y_train)

TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'float'

In [36]:
lr = MeraLR()

In [29]:
lr.fit(X_train,y_train)

0.5278637792004625
-0.768919327231524


In [32]:
lr.predict(X_test[0])

In [31]:
X_test[0]

np.float64(6.9)

In [37]:
print(lr.predict(X_test[0]))

6.9


AttributeError: 'MeraLR' object has no attribute 'm'

In [38]:
print("m =", lr.m)
print("b =", lr.b)
print(lr.predict(X_test[0]))

AttributeError: 'MeraLR' object has no attribute 'm'

In [43]:
lr = MeraLR()

In [45]:
print("m =", lr.m)
print("b =", lr.b)
print(lr.predict(X_test[0]))

m = None
b = None
6.9


TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

In [46]:
print(MeraLR.__dict__)

{'__module__': '__main__', '__firstlineno__': 1, '__init__': <function MeraLR.__init__ at 0x000001FAF3D27CE0>, 'fit': <function MeraLR.fit at 0x000001FAF3D27F60>, 'predict': <function MeraLR.predict at 0x000001FAF24B1C60>, '__static_attributes__': ('b', 'm'), '__dict__': <attribute '__dict__' of 'MeraLR' objects>, '__weakref__': <attribute '__weakref__' of 'MeraLR' objects>, '__doc__': None}


In [47]:
lr = MeraLR()
print(lr.__dict__)

{'m': None, 'b': None}


In [48]:
print(lr.predict(X_test[0]))

6.9


TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

In [49]:
lr.fit(X_train,y_train)

0.5278637792004625
-0.768919327231524


In [50]:
print(lr.predict(X_test[0]))

6.9
2.873340749251667


In [51]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [57]:
y_pred = lr.predict(X_test)

[6.9 8.9 5.3 8.  5.8 7.8 6.1 5.2 6.7 7.  9.1 7.2 7.2 8.9 5.  6.6 5.3 7.2
 8.8 7.6 6.9 4.6 7.2 4.7 5.9 6.1 6.4 6.3 5.4 8.8 8.8 8.2 6.6 8.4 7.6 5.3
 5.1 8.6 6.7 7.  8.9]


In [54]:
y_test

array([2.58, 3.22, 1.98, 3.85, 2.52, 3.82, 2.35, 1.88, 1.98, 3.05, 3.95,
       3.45, 3.15, 4.58, 1.65, 2.92, 2.1 , 2.45, 3.82, 2.68, 3.22, 1.5 ,
       3.28, 1.52, 2.75, 2.02, 1.88, 2.82, 1.6 , 4.08, 3.55, 3.82, 2.35,
       3.72, 3.85, 2.32, 2.32, 4.02, 3.05, 2.38, 4.18])

In [58]:
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 0.3247468705541487


In [59]:
print("MSE",mean_squared_error(y_test,y_pred))

MSE 0.14497683323031166


In [60]:
print("RMAE",np.sqrt(mean_absolute_error(y_test,y_pred)))

RMAE 0.5698656600938056


In [61]:
print("R2 Score",r2_score(y_test,y_pred))

R2 Score 0.7934436064543718


In [62]:
print("Adjusted R2 Score",r2_score(y_test,y_pred))
r2 = r2_score(y_test,y_pred)

Adjusted R2 Score 0.7934436064543718


In [63]:
X_test.shape

(41,)

In [64]:
1 - ((1-r2)*(41-1)/(40-1-1))

0.7825722173203914